Fix 'command not found' errors under different circustamces
bitnami/bitnami-docker-phabricator pull request #169
Opened 2021-02-23 12:07 UTC by juan131

**Description of the change**

The **PATH** environment variable is reseted under certain circumstances (e.g. when using `sudo` to execute commands as a different user, when accessing via SSH, etc.). This is highly problematic when you try to use Phabricator to host your repositories and access them via SSH because:

- You need to access the container via SSH using a **PHABRICATOR_SSH_VCS_USER** user.
- SSH daemon is configured to use Phabricator CLI to check authorised keys (requires customisations at `/etc/ssh/sshd`).
- The **PHABRICATOR_SSH_VCS_USER** user needs to perform some actions as the **PHABRICATOR_DAEMON_USER** user (requires `/etc/sudoers` customisations).
- Nor `php` nor `git` related commands are in default linux paths. 

I tried to fix it using different approaches:

- Disabling `env_reset` in `/etc/sudoers`.
- Using `PermitUserEnvironment yes` in `/etc/ssh/sshd_config`.
- Adding the **PATH** to `/etc/environment`.
- Adding the **PATH** to `/home/git/.ssh/environment` and `/home/phabricator/.ssh/environment`.

I got some progress using some of these fixes, but it still complains when performing some actions such as pushing commits. So I decided to use a totally different approach: using symlinks.

Using symlinks that points from `/usr/bin` to the directories where we're actually mounting these utilities, I could make it work. This is probably not the best solution, but it's a valid solution while we 

**Benefits**

Users can actually use Phabricator with hosted repositories using SSH authentication.

**Possible drawbacks**

Kind of "hacky" solution

**Applicable issues**

- https://github.com/bitnami/bitnami-docker-phabricator/issues/166

2021-02-23 12:27 UTC, marcosbc requested changes

2021-02-23 12:27 UTC, marcosbc commented on 2021/debian-10/rootfs/opt/bitnami/scripts/phabricator/setup.sh
> +    done
I'm not convinced with this. In the Provisioner tool we're adding PATH to these files:

    /root/{.bashrc,.profile}
    /home/*/{.bashrc,.profile}
    /etc/skel/{.bashrc,.profile}

You could also try and define `secure_path` in sudoers with an appropriate value to include Git.

And finally, if none of those convince you, try adding `PATH` to `env_keep` option in sudoers.

2021-02-23 12:35 UTC, javsalgar commented on 2021/debian-10/rootfs/opt/bitnami/scripts/phabricator/setup.sh
> +    done
I think the provisioner approach could work in this case. I imagine that in the Phabricator VM we don't find these issues, right?

2021-02-23 16:44 UTC, juan131 commented on 2021/debian-10/rootfs/opt/bitnami/scripts/phabricator/setup.sh
> +    done
@marcosbc the `secure_path` + `env_keep` made the trick.

2021-02-23 17:15 UTC, marcosbc commented on 2021/debian-10/rootfs/opt/bitnami/scripts/phabricator/setup.sh
> +    visudo -c -q -f "$sudoers_tmp" && cat "$sudoers_tmp" > /etc/sudoers
This seems to be checking the format of the new sudoers file. If so, could you describe that in a comment? Same below

2021-02-23 17:15 UTC, marcosbc commented on 2021/debian-10/rootfs/opt/bitnami/scripts/phabricator/setup.sh
> +    replace_in_file "$sudoers_tmp" "^Defaults\s+secure_path=\"(.*)\"$" "Defaults\tsecure_path=\"\1:$(command -v git | xargs dirname):$(command -v php | xargs dirname)\""
Could you describe what is happening here in a comment? Same below

2021-02-24 09:08 UTC, javsalgar commented on 2021/debian-10/rootfs/opt/bitnami/scripts/phabricator/setup.sh
> +    cat /etc/sudoers > "$sudoers_tmp"
Any reason for not using `cp`?

2021-02-24 09:31 UTC, juan131 commented on 2021/debian-10/rootfs/opt/bitnami/scripts/phabricator/setup.sh
> +    cat /etc/sudoers > "$sudoers_tmp"
Switching to `cp` after reading this: https://unix.stackexchange.com/questions/30295/cp-vs-cat-to-copy-a-file

2021-02-24 14:55 UTC, marcosbc approved these changes
LGTM!

2021-02-24 16:10 UTC, merged